### ISSUE TITLE
Uncaught TypeError: Cannot read property '153' of undefined

### ISSUE THREAD

**Issue by henrytseng** [samu/blocky#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [blocky](https://github.com/samu/blocky) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '153' of undefined

```
At /Users/henry/.atom/packages/blocky/lib/blocky-view.coffee:42

TypeError: Cannot read property '153' of undefined
    at BlockyView.module.exports.BlockyView.notifyChangeCursorPosition (/Users/henry/.atom/packages/blocky/lib/blocky-view.coffee:42:25)
    at /Users/henry/.atom/packages/blocky/lib/blocky-view.coffee:17:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1686:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:926:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:342:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:135:19)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:175:32)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:185:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1476:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1680:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1475:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:704:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -4:45.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -4:44.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:44.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:26.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:24.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:07.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:06.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:16.3.0 editor:outdent-selected-rows (div.package-detail.panels-item)
     -0:16.2.0 core:save (atom-text-editor.editor.is-focused)
  8x -0:12.9.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:11.5.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -0:11 core:move-down (atom-text-editor.editor.is-focused)
  8x -0:10.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:close (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
blocky, v0.1.0
docblockr, v0.7.3
language-haml, v0.23.15
language-scala, v1.1.6
linter, v1.11.3
linter-eslint, v7.1.1
linter-ruby, v1.2.2
linter-scalac, v1.4.0
scala-format, v0.1.8
split-diff, v0.6.0

# Dev
No dev packages
```

**Comment by samu** [comment]
Should be fixed with 287ac3a5b91393e4cd8fcb096c004e4412ef6f73
